#----------------------------------------------------------------------#
#    _   _   _       _          _   _   ____                  _        #
#   | | | | (_)   __| |   ___  | \ | | / ___|    ___    ___  | | __    #
#   | |_| | | |  / _` |  / _ \ |  \| | \___ \   / _ \  / _ \ | |/ /    #
#   |  _  | | | | (_| | |  __/ | |\  |  ___) | |  __/ |  __/ |   <     #
#   |_| |_| |_|  \__,_|  \___| |_| \_| |____/   \___|  \___| |_|\_\    #
#                                                                      #
#----------------------------------------------------------------------#


MinimumPlayers: 4

MinimumPlayers_With_Vote: 2

# Time must be more than Send_Seeker_after_seconds 

Time: 600

Auto_Start_Time: 20

Send_Seeker_after_seconds: 60

TagStick:
  
  display_name: '&a&lTag Stick'
  lore: 
  - ' '
  - '&2Hit a hider with this'
  - '&2stick to tag him.'

Rewards:

# These commands will be run by Console/Not player

  Seekers:
    Message: '&aYou won 10 XP points and 200 money!'
    Commands:
      1: 'money add %player% 200'
      2: 'experience add %player% 10'
      
  Hiders:
    Message: '&aYou won 10 XP points and 200 money!'
    Commands:
      1: 'money add %player% 200'
      2: 'experience add %player% 10'

Shop:
  
  Rows: 3
  
  Fill_Empty_Slot:
    Item: BLACK_STAINED_GLASS_PANE
    display_name: ' '
    lore:
    
  Items:
  
    1:
      isItem: false
      isPotion: true
      Slot: 0
      PotionType: JUMP
      PotionLength: 60
      PotionStrength: 1
      Price: 100
    
    2:
      isItem: false
      isPotion: true
      Slot: 1
      PotionType: SPEED
      PotionLength: 60
      PotionStrength: 1
      Price: 100
    
    3:
      isItem: false
      isPotion: true
      Slot: 2
      PotionType: INVISIBILITY
      PotionLength: 60
      PotionStrength: 1
      Price: 100
      
    4: 
      isItem: true
      isPotion: false
      Slot: 3
      ItemType: FIREWORK_ROCKET
      Amount: 2
      Price: 100
      